In [ ]:
print("day-3")

day-3


# Tuple

In [1]:
t1 = (1,2,3,"ntt",4)

In [2]:
t1

(1, 2, 3, 'ntt', 4)

In [3]:
print(type(t1))

<class 'tuple'>


In [4]:
t2 = tuple((1,2,3,"ntt",4))

In [5]:
print(t2)

(1, 2, 3, 'ntt', 4)


In [6]:
print(type(t2))

<class 'tuple'>


In [7]:
t3 = tuple([1,2,3,"ntt",4])

In [8]:
type(t3)

tuple

In [10]:
t4 = tuple([15])
type(t4)

tuple

In [12]:
t5 = tuple((5,)) # please give a ',' to make the number iterable , because the tuple() method expects an iterable object
type(t5)

tuple

In [14]:
t6 = tuple(("ntt"))
print(t6)
type(t6)

('n', 't', 't')


tuple

In [17]:
t7 = tuple(("ntt",1,15,"Bijith"))
print(t7)
type(t7)

('ntt', 1, 15, 'Bijith')


tuple

In [18]:
for i in t7:
  print(i)

ntt
1
15
Bijith


In [21]:
print(t7[0])
print(t7[-1])
print(t7[2:4])
print(t7[2:])
print(t7[-4:-1])

ntt
Bijith
(15, 'Bijith')
(15, 'Bijith')
('ntt', 1, 15)


In [22]:
t7[0] = 100

TypeError: 'tuple' object does not support item assignment

In [24]:
t8 = list(t7)
print(t8)
type(t8)

['ntt', 1, 15, 'Bijith']


list

In [25]:
t8[0] = 100
print(t8)

[100, 1, 15, 'Bijith']


In [26]:
del t7 # delete tuple t7

# Dictionary

In [30]:
d1 = {"name": "Bijith","age":48,"course":"Msc"}

print(d1)
print(d1["name"])
type(d1)

{'name': 'Bijith', 'age': 48, 'course': 'Msc'}
Bijith


dict

In [31]:
d2 = {"usn1": ["Bijith",48,"Msc"]}
print(d2)

{'usn1': ['Bijith', 48, 'Msc']}


In [32]:
d3 = dict(name="Bijith",age=48, course="Msc")
print(d3)

{'name': 'Bijith', 'age': 48, 'course': 'Msc'}


In [33]:
print(d3.keys())

dict_keys(['name', 'age', 'course'])


In [34]:
print(d3.values())

dict_values(['Bijith', 48, 'Msc'])


In [35]:
print(d3.items())

dict_items([('name', 'Bijith'), ('age', 48), ('course', 'Msc')])


In [37]:
d3["name"] = "Bijith Komalan"
print(d3)

{'name': 'Bijith Komalan', 'age': 48, 'course': 'Msc'}


In [38]:
d3.update({"course": "Msc,MCA"})

In [39]:
d3

{'name': 'Bijith Komalan', 'age': 48, 'course': 'Msc,MCA'}

In [40]:
d3['country'] = "India"
d3

{'name': 'Bijith Komalan', 'age': 48, 'course': 'Msc,MCA', 'country': 'India'}

In [41]:
#removing a particular key in dict
d3.pop("course")
d3

{'name': 'Bijith Komalan', 'age': 48, 'country': 'India'}

In [42]:
#remove the last key in the dict
d3.popitem()
d3

{'name': 'Bijith Komalan', 'age': 48}

In [43]:
#deleting a particulat element
del d3["name"]
d3

{'age': 48}

In [44]:
# deleting a dict
del d3

In [45]:
for key,val in d2.items():
  print(key, val)

usn1 ['Bijith', 48, 'Msc']


# Numpy

In [46]:
import numpy as np

In [47]:
arr = np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [50]:
#two know the dimension of the aary
print(arr.ndim)
#size of the array
print(arr.size)
# shape of the arry , #no of rows and cols, always returned as tuple
print(arr.shape)
# data type of array
print(arr.dtype)

1
5
(5,)
int64


In [52]:
#creating 2d array with numpy
arr2d = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr2d)
#two know the dimension of the aary
print(type(arr2d))
print(arr2d.ndim)
#size of the array
print(arr2d.size)
# shape of the arry , #no of rows and cols, always returned as tuple
print(arr2d.shape)
# data type of array
print(arr2d.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
6
(2, 3)
int64


In [62]:
#creating 3d array with numpy
arr3d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
      [7,8,9],
      [10,11,12]
    ]
])
print(arr3d)
#two know the dimension of the aary
print(type(arr3d))
print(arr3d.ndim)
#size of the array
print(arr3d.size)
# shape of the arry , #no of rows and cols, always returned as tuple
print(arr3d.shape)
# data type of array
print(arr3d.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3
12
(2, 2, 3)
int64


In [66]:
#creating 4d array with numpy
arr4d = np.array([[
    [
        [1,2,3],
        [4,5,6]
    ],
    [
      [7,8,9],
      [10,11,12]
    ]
]])
print(arr4d)
#two know the dimension of the aary
print(type(arr4d))
print(arr4d.ndim)
#size of the array
print(arr4d.size)
# shape of the arry , #no of rows and cols, always returned as tuple
print(arr4d.shape)
# data type of array
print(arr4d.dtype)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
<class 'numpy.ndarray'>
4
12
(1, 2, 2, 3)
int64


In [67]:
#creating 5d array with numpy
arr5d = np.array([[[
    [
        [1,2,3],
        [4,5,6]
    ],
    [
      [7,8,9],
      [10,11,12]
    ]
]]])
print(arr5d)
#two know the dimension of the aary
print(type(arr5d))
print(arr5d.ndim)
#size of the array
print(arr5d.size)
# shape of the arry , #no of rows and cols, always returned as tuple
print(arr5d.shape)
# data type of array
print(arr5d.dtype)

[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]]]
<class 'numpy.ndarray'>
5
12
(1, 1, 2, 2, 3)
int64


single line -> 1d
multiple lines in a page -> 2d
stacking of these pages in a book -> 3d
stacking of books in a shelf -> 4d
stacking of shelfs in a rack -> 5d
stacking of racks in a row -> 6d
stacking of rack rows in a library -> 7d